### ISSUE TITLE
Switch requiring of specific models to new global module

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server#15]
In [`utils/login.js`](https://github.com/ScienceDb/graphql-server/blob/master/utils/login.js) line 3 
```const user = require('../models_index').user;```
raises an error:
```Error: Cannot find module '../models/index'```

That is because we switched to single central import for _all_ models regardless of there backend storage technology via [`models_index.js`](https://github.com/ScienceDb/graphql-server/blob/master/models_index.js).

Check the whole projects `graphql-server` and `graphql-server-model-codegen` for outdated model imports and fix them. Write tests were necessary and applicable. To this efficiently use something like 
```
find . -type f -iname '*js' -exec grep -ilP 'require.*models_index' \{\} \;
```

Please commit the fix in a single well encapsulated commit so that that specific commit can be used in a `git cherry-pick` to fix this bug in other branches.

**Comment by asishallab** [comment]
Fixed in project `graphql-server` with commit [`a4a7784585ddbf35356f264f50321e0f1dae8a97`](https://github.com/ScienceDb/graphql-server/commit/a4a7784585ddbf35356f264f50321e0f1dae8a97). Login should now work again.

Please check project `graphql-server-model-codegen` using the same approach with `find ...`.

### Actual work time for the `graphql-server` project: 7 minutes

**Comment by YKolokoltsev** [comment]
Tested and closed
