### ISSUE TITLE
Fix logging of loaded models in `./models_index.js`

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server#23]
The loader module `./models_index.js` implements loading and initializing all models of all storage types. However, only models of type `sql` get logged to the console as being loaded. This is highly misleading. Please fix and please improve the log message to something like 

`loaded model: ${iterModel.name}`

### Expected work time: 1h

**Comment by coeit** [comment]
commit: https://github.com/ScienceDb/graphql-server/commit/c4999be668425b0f723f97475f510b062e003bbd
