### ISSUE TITLE
Implement extended (meta) search allowing to filter results with "jq" or "jsonPath"

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server#24]
For a full and detailed description of the Issue, please see this [whitepaper](https://docs.google.com/document/d/121ACqaIn7qnfNl4sKruPNTT63r4jwF3o1I21RqZRzA4/edit?usp=sharing)

**Comment by tmvoe** [comment]
Commits cb68de5b55663f2087e2076b2c37aeea8b5bb4ed
fe2e6f04a2bb81429f19aa07640ecb2e939ed6ec
3c498021fc2538c22e752b588204f7894a10a395
24e4dabeb47a296afd3232c161b7fb38e342461e
7e7b18a962fef73983222bb128392b00e72212b6
a09c6fe5abd0207af244d8c94b3d52fc0a475562
9c7879141cabbab981f7d8571d6146a3254d4b1e
cfed3a91fa7143ddf8194fe96ba6ecd4122900e3
8756f3051bc734575a06ad23f2a650a3a67e4fa3
b62f0ba73377ee9c8a25c797e12a7d6653e3a9af
16dc8313d72d85799abed439dab6bd21c51d5bd6
a93030fd9206cfea820da90528ab44f302170e0f

**Comment by tmvoe** [comment]
Resolved by merging `issue24-extendedSearch`.
