### ISSUE TITLE
Implement User-model, authentication, and authorization

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server#6]
### User model and routes

Provide a complete user model and resolvers to manipulate user records through GraphQL. Consider using our code generators for this step. Include this in the default branch of `graphql-server`.

Definition of the `user` model:
- id
- email: unique
- password
- roles

The above shows that we need a model `role`:
- id
- name: unique
- description

And a cross table for the many-to-many relation.

One additional route should be implemented: `login` 

#### Add default roles and user

Put an `admin` role into the ACL rules. Only the admin has the right to access resolvers to the `user` model.

### Integrate Authentication into GraphQL with Express

Write a module `authenticationMiddleware` which can be required and then `use`d in express:
`app.use(authenticatioMiddleware)`.

[Consider this oficial documentation](https://graphql.org/graphql-js/authentication-and-express-middleware/) and use express-jwt to handle the management of JWT tokens, including login.

If a resolver requires a logged in user or even authorization, then a token should be looked up in the request header, and the matching user read from the database, including his/her roles.

Use [`express-jwt`](https://www.npmjs.com/package/express-jwt) and [this general application layout](http://jasonwatmore.com/post/2018/08/06/nodejs-jwt-authentication-tutorial-with-example-api) to implement login and authentication from the JWT token. 

`login`  can be realized using RESTful routes and _not_ GraphQL resolvers.

_Note_: [There is no logout with JWT](https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6)

**Comment by vsuaste** [comment]
Done. Commits [#aa041d](https://github.com/ScienceDb/graphql-server/commit/aa041d0ab6529ffdbc29a5d8d5bf4cfd816e5b27) [#acf11ba](https://github.com/ScienceDb/graphql-server/commit/acf11ba386ff9d079fd25d2f503242a47dc52bde) [#865801](https://github.com/ScienceDb/graphql-server/commit/8658019ad625855d4827e93acd3558bfd910663e) [fcd200](https://github.com/ScienceDb/graphql-server/commit/fcd2007d23b8e86ea9f5ecad87b38605720b417c)
