### ISSUE TITLE
Add environment variable PORT that is used to define on which port the server is listening

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server#9]
Currently PORT is statically set to `3000` on line `19` of [`server.js`](https://github.com/ScienceDb/graphql-server/issues/1).

Please retain `3000` as default but also enable setting this variable to an environment variable `PORT`. 

Add documentation in both the README and our manual.

### Expected work time: 20 Minutes

**Comment by vsuaste** [comment]
Done. Commits: [#940812](https://github.com/ScienceDb/graphql-server/commit/940812e19a5e42210319ab87d8698d93179329c5) [#35f23ec](https://github.com/ScienceDb/graphql-server/commit/35f23ec99e2ed92a84ecc6a3e4dc9c3be6d0346f) [#5e0566](https://github.com/ScienceDb/graphql-server/commit/5e0566c3faacab374c30ac686eb981d4d61a2e5d) [#050ded](https://github.com/ScienceDb/ScienceDb.github.io/commit/050ded37b578d3d2f79fe81b0162d9b876a5ba84)
### Actual work time: 40 minutes
